version: '3.8'
services:
  company-api:
    container_name: company-api
    networks:
      - emarket-network
    build:
      context: company-api
      dockerfile: Dockerfile
    image: company-api:latest
    ports:
      - 8081:8081
    depends_on:
      - dynamodb-local
    links:
      - dynamodb-local
    environment:
        REGION: 'eu-west-1'


  stock-api:
    container_name: stock-api
    networks:
      - emarket-network
    build:
      context: stock-api
      dockerfile: Dockerfile
    image: stock-api:latest
    ports:
      - 8070:8070
    depends_on:
      - mysql
    #restart: on-failure
    links:
      - mysql

#  mongodb:
#    image: mongo:latest
#    container_name: mongodb
#    networks:
#      - emarket-network
#    ports:
#      - 27017:27017
#    restart: always
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  mysql:
    platform: linux/x86_64
    image: mysql:8.0.25
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - emarket-network
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: stockdb
      MYSQL_USER: stock-api-user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      start_period: 30s

  eureka-discovery:
    container_name: 'eureka-discovery'
    networks:
      - emarket-network
    build:
      context: eureka-discovery
      dockerfile: Dockerfile
    image: eureka-discovery:latest
    ports:
      - 8075:8075

  cloud-gateway:
    container_name: 'cloud-gateway'
    networks:
      - emarket-network
    build:
      context: cloud-gateway
      dockerfile: Dockerfile
    image: cloud-gateway:latest
    ports:
      - 8060:8060

networks:
  emarket-network:
    driver: bridge